### PR TITLE
Replace `untyped __js__` by `js.Syntax.code`

### LINKED ISSUE #15: Haxe 4.1.0: __js__ is deprecated, use js.Syntax.code instead
When using this package with Haxe 4.1.0 and compiling to Node.js target, I get this deprecation warning:

`tink_chunk/0,3,1/src/tink/chunk/nodejs/BufferChunk.hx:49: characters 17-23 : Warning : __js__ is deprecated, use js.Syntax.code instead`

This is not blocking, but annoying to activate the `no-deprecation-warnings` compiler flag.

### PR DESCRIPTION
**Pull request by CedX**
Fixes #15

### CODE REVIEW

**Comment by CedX** [comment]
`Buffer.allocUnsafe` was added to Node.js in v5.10.0: we could probably simplify this code by removing the check and the `alloc` property. Node.js v5 is pretty old: the current LTS release is v12.

**Comment by kevinresol** [comment]
> `Buffer.allocUnsafe` was added to Node.js in v5.10.0: we could probably simplify this code by removing the check and the `alloc` property. Node.js v5 is pretty old: the current LTS release is v12.

I agree.

**Comment by CedX** [comment]
@kevinresol Done.

**Comment by kevinresol** [comment]
Thanks!

**Pull request merged**
